spring.application.name=finwing
spring.datasource.username=postgres
spring.datasource.url=jdbc:postgresql://monorail.proxy.rlwy.net:57581/railway?sslmode=require&options=-c%20TimeZone=Asia/Kolkata
spring.datasource.password=DowCbSLenAnmRiELpjyXvkBkQzImQMva


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
server.address=0.0.0.0
server.port=${PORT:8080}
spring.jpa.hibernate.ddl-auto=update